import { BaseService } from "./baseService";
import { DecodedIdToken, getAuth } from "firebase-admin/auth";

export class AuthenticationService extends BaseService {
  /**
   * Registers a new user
   *
   * @param user name and uid of user to register
   * @returns newly created user object
   */
  public async registerUser(name: string, idToken: string) {
    let uid: string;

    try {
      uid = (await this.verifyFirebaseIdToken(idToken)).uid;
    } catch {
      throw new Error("Failed to verify id token");
    }

    const existingUser = await this.prisma.user.findFirst({
      where: {
        uid: {
          equals: uid,
        },
      },
    });

    if (existingUser) {
      throw new Error(`User with uid ${uid} already exists`);
    }

    const newUser = await this.prisma.user.create({
      data: {
        name,
        uid,
      },
    });

    return newUser;
  }

  /**
   * Verifies a temporary id token from the client.
   *
   * @param idToken Id Token generated by client firebase login
   * @returns uid of verified user
   */
  private async verifyFirebaseIdToken(idToken: string) {
    let token: DecodedIdToken;

    try {
      token = await getAuth().verifyIdToken(idToken);
    } catch {
      throw new Error("Failed to verify id token");
    }

    return {
      uid: token.uid,
    };
  }

  /**
   * Creates a new session token for a new client login
   *
   * @param idToken Temporary id token from the client
   * @returns New session token
   */
  public async createSessionToken(idToken: string) {
    try {
      await this.verifyFirebaseIdToken(idToken);
    } catch {
      throw new Error("Failed to verify id token");
    }

    const sessionToken = await getAuth().createSessionCookie(idToken, {
      expiresIn: 60 * 60 * 24 * 5 * 1000, // 5 days
    });

    return {
      sessionToken,
    };
  }

  /**
   * Verifies a session token
   *
   * @param sessionToken Session token to verify
   * @returns uid of verified user
   */
  public async verifySessionToken(sessionToken: string) {
    let decodedClaims: DecodedIdToken;

    try {
      decodedClaims = await getAuth().verifySessionCookie(sessionToken, true);
    } catch {
      throw new Error("Session token is invalid");
    }

    return {
      uid: decodedClaims.uid,
    };
  }
}
